import {STAGE, EMPLOYEE_DEV_API_BASE_URL, EMPLOYEE_TEST_API_BASE_URL, EMPLOYEE_PROD_API_BASE_URL} from "@env";

const EMPLOYEE_API_BASE_URL = STAGE === "dev" ? EMPLOYEE_DEV_API_BASE_URL : (STAGE === "test" ? EMPLOYEE_TEST_API_BASE_URL : EMPLOYEE_PROD_API_BASE_URL);

export const MOBILE_ONBOARD_API = `${EMPLOYEE_API_BASE_URL}/mobile`;
export const AADHAR_ONBOARD_API = `${EMPLOYEE_API_BASE_URL}/aadhaar`;
export const PAN_ONBOARD_API = `${EMPLOYEE_API_BASE_URL}/pan`;
export const BANK_ONBOARD_API = `${EMPLOYEE_API_BASE_URL}/bank`;
export const PROFILE_ONBOARD_API = `${EMPLOYEE_API_BASE_URL}/profile`;
export const GET_DOCUMENTS_API = `${EMPLOYEE_API_BASE_URL}/documents`;
