export const MOBILE_ONBOARD_API ="https://wq1kbvpl4b.execute-api.ap-south-1.amazonaws.com/dev/employee/mobile"
export const AADHAR_ONBOARD_API ="https://wq1kbvpl4b.execute-api.ap-south-1.amazonaws.com/dev/employee/aadhaar"
export const PAN_ONBOARD_API ="https://wq1kbvpl4b.execute-api.ap-south-1.amazonaws.com/dev/employee/pan"
export const BANK_ONBOARD_API ="https://wq1kbvpl4b.execute-api.ap-south-1.amazonaws.com/dev/employee/bank"
export const PROFILE_ONBOARD_API ="https://wq1kbvpl4b.execute-api.ap-south-1.amazonaws.com/dev/employee/profile"
export const GET_DOCUMENTS_API ="https://wq1kbvpl4b.execute-api.ap-south-1.amazonaws.com/dev/employee/documents"