/* eslint-disable quotes */
export default {
  // WelcomePage.jsx
  phoneVerificationSuccess: "Your phone number was verified successfully.",
  completeEkyc:
    "As a next step please complete your eKYC to get money in your bank account",
  startEkyc: "Start eKYC",
  // ProfileForm.jsx
  onboarding: "Onboarding",
  tellUsAboutYou: "Tell us about you",
  incorrectFormat: "Incorrect Format",
  continue: "Continue",
  whatsappPlaceholder: "Your whatsapp mobile no.",
  motherNamePlaceholder: "Mother's Name*",
  maritalStatusPlaceholder: "Select Maritial Status*",
  educationPlaceholder: "Select Education*",
  emailPlaceholder: "Your email ID",
  holdOnBack: "Are you sure you want to go back?",
  aadhaarNumber: "Aadhaar Number",
  agreeKycTNC:
    "I agree with the KYC registration Terms & Conditions to verifiy my identity. You will receive an OTP to your Aadhaar registered mobile number.",
  invalidAadhaarNumber: "Invalid Aadhaar Number",
  enterAadhaarNumber: "Enter your Aadhaar number",
  wait10Minutes: "You must wait for 10 minutes to resend OTP.",
  holdOn: "Hold on!",
  goBackEditAadhaar:
    "Are you sure you want to go back? Continue if you want to edit your Aadhaar number.",
  verifyAadhaar: "Verify Aadhaar",
  otpNotReceived: "Didn’t receive the secure code?",
  resendOtp: "Resend OTP in",
  goBackAadhaarVerification:
    "If you go back your Aadhaar Verification will have to be redone. Continue only if you want to edit your Aadhaar number.",
  areTheseAadhaarDetails: "Are these your Aadhaar details?",
  notMe: "Not Me",
  yesMe: "Yes, that’s me",
  enterPanNumber: "Enter your PAN number",
  forgotPan: "Forgot PAN?",
  agreeKycTNCPan:
    "I agree with the KYC registration Terms & Conditions to verifiy my identity. PAN is required to verify name and date of birth.",
  verifyAadhaarFirst: "Please verify your aadhaar first",
  invalidPanNumber: "Invalid PAN Number.",
  goBack: "Do you want to go back ?",
  areThesePanDetails: "Are these your PAN details?",
  goBackPanVerification:
    "If you go back your PAN Verification will have to be redone. Continue only if you want to edit your PAN number.",
  bankAccountDetails: "Bank Account Details",
  referToPassbook:
    "Refer to your Bank Passbook or Cheque book for the exact Name mentioned in your bank records",
  accountHolderName: "Account Holder Name*",
  bankAccountNumber: "Bank Account Number*",
  refertoGetAccountNumber:
    "Refer to your Bank Passbook or Cheque book to get the Bank Account Number.",
  ifscCode: "IFSC Code*",
  findIfscCode:
    "You can find the IFSC code on the cheque book or bank passbook that is provided by the bank",
  upiId: "UPI ID",
  lotsOfUpiApps:
    "There are lots of UPI apps available like Phonepe, Amazon Pay, Paytm, Bhim, Mobikwik etc. from where you can fetch your UPI ID.",
  agreeWithKycRegistration:
    "I agree with the KYC registration Terms & Conditions to verifiy my identity. We will use this bank account/UPI ID to deposite your salary every month, Please provide your own bank account details.",
  detailsSafe: "All your details are safe with us",
  goBackBankVerification:
    "If you go back your Bank Verification will have to be redone. Continue only if you want to edit your Bank Account Details.",
  areTheseBankDetails: "Are these your Bank Account details?",
  continuePanVerification: "Continue to PAN Verification",
  continueBankVerification: "Continue to Bank Verification",
  bankName: "Bank Name",
  branchName: "Branch Name",
  branchCity: "Branch City",
  ifscCodeSingle: "IFSC",
  upi: "UPI",
  verifyStatus: "Verify Status",
  editProfileDetails: "See & edit your profile details",
  kycDetailsInOnePlace: "All your KYC details in one place",
  customerSupport: "Customer Support",
  termsAndConditions: "Terms & Conditions",
  privacyPolicy: "Privacy Policy",
  talkToSupportTeam: "Talk to out support team",
  readTermsOfUse: "Read our terms of use",
  readPrivacyPolicy: "Read our privacy policy",
  logout: "Logout",
  logoutFromUnipe: "Logout from Unipe App",
  choosePreferredMode: "Please choose your preferred mode",
  initializing: "Initializing ...",
  mandateRegistrationInProgress:
    "Your Mandate Registration is currently in progress.",
  MandateRequired:
    "Mandate is required to auto-debit loan payments on Due Date. This is 100% secure and executed by an RBI approved entity.",
  secured: "100% Secure",
  rbiApproved: "RBI Approved",
  updatingMandate: "Updating mandate registration details",
  mayTakeFewSeconds: "This may take few seconds",
  dontPressBack: "Please don't press the back button",
  mandateFailed: "Mandate Registration Failed, Please Try Again",
  employeeAddressDetailsRecorded: "Employee Address details recorded.",
  nomineeAddress: "Nominee Address",
  portal: "Portal",
  familyDetails: "Family Details",
  yourAddress: "Your Address",
  nomineeAddressDetailsRecorded: "Nominee Address details recorded.",
  esicPortalDetailsRecorded: "ESIC Portal details recorded.",
  fatherName: "Father's / Husband's Name*",
  relationWithEmployee: "Relation with Employee (Father/Husband)*",
  nameOfNominee: "Name of Nominee (As per Aadhaar card)*",
  nomineeRelationship: "Nominee Relationship with Employee*",
  documents: "Documents",
  moreDetailsComingSoon: "More Details Coming Soon",
  dateOfBirth: "Date of birth as recorded in License",
  licenseNeeded:
    "License is needed to verify your eligibility to operate heavy machinery.",
  expiryDate: "Expiry date",
  nonTransport: "Non-Transport",
  valid: "Valid",
  invalid: "Invalid",
  licenseDetailsNotEditable:
    "The License Details are not editable, please ask your employer to update",
  unipeP2PHeading:
    "Unipe Invest is a P2P investment that earns you upto 9% interest on your investments",
  poweredByLiquiloans: "We are powered by Liquiloans, RBI regulated P2P NBFC.",
  interestEarned:
    "Interest earned will be earned daily and you are free to withdraw your investment and earnings at any time",
  welcomeToUnipeInvest: "Welcome to Unipe Invest.",
  designedToMultiply: "Designed to multiply your growth",
  knowMore: "Know more",
  youAreOnly: "You are only",
  steps: "2 steps",
  awayFromMakingInvestment: "away from making your first investment",
  proceedToVerifyAndGrowWealth:
    "proceed to verify your details and start growing your wealth.",
  howItWorks: "How it works?",
  joinedWaitlist: "You've joined the waitlist for Unipe Invest!!",
  rbiRegisteredNBFC: "an RBI registered NBFC-P2P",
  p2pInvestment: "What is P2P investment?",
  peerToPeerInvestment:
    "Peer 2 Peer investment allows you to invest money against loans given to borrows and is done by our RBI regulated partner",
  benefitsOfP2P: "What are the benefits of P2P investment?",
  p2pLendingRBI:
    "P2P lending is regulated by RBI. We have partnered with Liquiloans to offer investment products\n\nP2P investment gives opportunity to earn more than traditional deposit products",
  risksOfP2P: "What are the risks associated with P2P investment?",
  p2pRisks:
    "Like any other investment product P2P investment also has associated risk like performance of loans and repayment of borrowers affect your returns\n\nGood News is Our partner has honoured 100% withdrawal within 48 Hrs.\n\nAlso our partner investment product is rated as AA- (by CRISIL) which is one of the highest in the industry",
  whyInvestWithUnipe: "Why invest with Unipe?",
  earnHighReturns:
    "You can earn inflation beating highest returns for your investment\n\nYour principal and base interest is secured at our RBI regulated partner",
  knowMoreAboutP2P: "Know more about P2P investment",
  howMuch: "How much do you want?",
  accessOfEF: "Here is your access of emergency funds",
  zeroInterest: "Zero Interest charges, Nominal Processing Fees",
  iAgree: "I agree to the",
  TermsAndConditions: "Terms and Conditions",
  processing: "Processing",
  areTheseKycDetails: "Are these your Kyc details?",
  processingFees: "Processing Fees †",
  disAmount: "Disbursement Amount *",
  loanAmount: "Loan Amount",
  dueDate: "Due Date",
  loanDetails: "Loan Details",
  bankDetails: "Bank Details",
  moneyWillBeAutoDebited:
    "*Money will be either auto debited or deducted by your employer from your upcoming salary.",
  personalDetails: "Personal Details",
  aboveDetails: "I confirm the above details and agree to",
  apr: "† Annual Percentage Rate @",
  congrats: "Congratulations",
  advanceSalaryCredited:
    "Your advance salary has been credited to your bank account.",
  sorry: "Sorry",
  cannotProcessSalary: "We cannot process your advance salary at this moment.",
  pending: "Pending",
  receiveMoney: "You will receive the money in next 24 banking hours.",
  netTransferAmount: "Net Transfer Amount",
  loanAccountNumber: "Loan Account Number",
  transferStatus: "Transfer Status",
  moneyAutoDebitedUpcomingSalary:
    "Money will be auto debited from your upcoming salary",
  onDemandSalary: "Here is your On-Demand Salary",
  totalAmountDue: "Your total amount due",
  RepaymentDue: "Your repayment is overdue by <> days",
  pastDraws: "Your past draws",
  getYourSalaryToday: "Get your salary today!",
  enterMobileNumber: "Enter Mobile Number",
  getAdvancedSalaryToday: "Get Your Advance\nSalary Today",
  zeroInterestCharge: "0% Interest Charges",
  noJoiningFees: "No Joining Fees",
  interestInBank: "Instant cash in bank account",
  pleaseWaitOtp: "Please wait, we will auto verify the OTP sent to",
  verifyMobileNumber: "Verify mobile number",
  resendOtp: "Resend OTP",
  didnotReceiveOtp: "Didn’t receive the secure code?",
  resendOtpIn: "Resend OTP in",
  aadhaarVerification: "Aadhaar Verification",
  enterYourDetails: "Enter Your Details",
  verifyAadhaar: "Verify Aadhaar",
  panVerification: "PAN Card Verification",
  addBankAccount: "Add Bank Account",
  onDemandSalary: "On-Demand Salary",
  selectAmount: "Select amount you want to withdraw",
  confirmKyc: "Confirm KYC",
  confirmIfTheseDetails: "Please confirm if these are your details",
  confirmMyKyc: "I confirm my KYC",
  verifying: "Verifying",
  addRepaymentMethod: "Add Repayment Method",
  faq: "Frequently Asked Questions",
  proceed: "Proceed",
  name: "Name",
  panNumber: "PAN Number",
  dateOfBirth: "Date of Birth",
  moneyTransfer: "Money Transfer",
  verifyYourIdentity:
    "Verify your identity and complete your full KYC process to withdraw advance salary.",
  availableSalary: "Available Salary",
  withDrawAdvanceSalary: "Withdraw Advance Salary",
  kycPending: "KYC pending for Advance Salary",
  offerInactive: "Offer Inactive",
  getSalaryNow: "Get Salary Now",
  completeYourKyc: "Complete Your KYC",
  transfer: "Transfer ",
  toBankAccount: " to your Bank account in minutes",
  payNow: "Pay Now",
  inProgress: "In Progress",
  iWantToWithdraw: "I want to withdraw",
  bankAccount: "Bank Account",
  takeBusinessDays: "Takes upto 1 business day",
  withdrawalDeduction:
    "The withdrawl will be deducted from your upcoming paycheck",
  loanAgreement: "Loan Agreement",
  learnWithUs: "Learn With Us",
  getYouVerified: "Let’s get you verified",
  complete4Steps: "Complete the following 4 steps to verify your account ",
  step: "Step",
  goodAfternoon: "Good Afternoon",
  needHelp: "Need help?",
  clickHere: "Click here",
  stillNeedHelp: "Still need help?",
  getInTouch:
    "Have queries? please get in touch and we will be happy to help you",
  contactSupport: "Contact Support",
  explore: "Explore",
  loggingOut: "Logging you out...",
  logout: "Logout",
  amountDue: "Amount Due",
  noInternet: "No Internet",
  checkInternetConnection: "Please check your internet connection",
  refresh: "Refresh",
  rbiGuidelines:
    "As per RBI guidelines, you have to complete e-KYC to get Advance Salary",
  rbiApprovedLendingPartners: "RBI approved Lending Partners",
  transport: "Transport",
  pleaseNote:
    "Please note: We will use this bank account/UPI ID to deposite your salary every month, Please provide your own bank account details.",
};

