/* eslint-disable quotes */
export default {
  phoneVerificationSuccess: "आपका फ़ोन नंबर सफलतापूर्वक सत्यापित किया गया।",
  completeEkyc:
    "अगले चरण के रूप में कृपया अपने बैंक खाते में पैसा प्राप्त करने के लिए अपना ईकेवाईसी पूरा करें",
  startEkyc: "ईकेवाईसी शुरू करें",
  onboarding: "ऑनबोर्डिंग",
  tellUsAboutYou: "हमें अपने बारे में बताओ",
  incorrectFormat: "गलत स्वरूप",
  continue: "आगे बढ़े",
  whatsappPlaceholder: "आपका व्हाट्सएप मोबाइल नं.",
  motherNamePlaceholder: "मां का नाम*",
  maritalStatusPlaceholder: "वैवाहिक स्थिति का चयन करें*",
  educationPlaceholder: "शैक्षणिक योग्यता का चयन करें*",
  emailPlaceholder: "Your email ID",
  holdOnBack: "रुकिए! क्या आप वाकई वापस जाना चाहते हैं?",
  aadhaarNumber: "आधार नंबर",
  agreeKycTNC:
    "मैं अपनी पहचान वेरीफाई करने के लिए KYC पंजीकरण नियम और शर्तों से सहमत हूं। आपको अपने आधार पंजीकृत मोबाइल नंबर पर एक ओटीपी प्राप्त होगा।",
  invalidAadhaarNumber: "अमान्य आधार नंबर",
  enterAadhaarNumber: "अपना आधार नंबर दर्ज करें",
  wait10Minutes: "ओटीपी दोबारा भेजने के लिए आपको 10 मिनट तक इंतजार करना होगा।",
  holdOn: "रुकिए!",
  goBackEditAadhaar:
    "क्या आप वाकई वापस जाना चाहते हैं? अगर आप अपना आधार नंबर बदलना चाहते हैं तो जारी रखें।",
  verifyAadhaar: "आधार वेरीफाई करें",
  otpNotReceived: "क्या सुरक्षित कोड प्राप्त नहीं हुआ?",
  resendOtp: "फिर से ओटीपी भेजें",
  goBackAadhaarVerification:
    "अगर आप वापस जाते हैं तो आपका आधार वेरिफिकेशन दोबारा कराना होगा। यदि आप अपना आधार नंबर बदलना चाहते हैं तो ही जारी रखें।",
  areTheseAadhaarDetails: "क्या यह आपके आधार का विवरण हैं?",
  notMe: "नहीं",
  yesMe: "हाँ",
  enterPanNumber: "अपना PAN नंबर दर्ज करें",
  forgotPan: "PAN भूल गए?",
  agreeKycTNCPan:
    "मैं अपनी पहचान वेरीफाई करने के लिए KYC पंजीकरण नियम और शर्तों से सहमत हूं। नाम और जन्म तिथि वेरीफाई करने के लिए PAN आवश्यक है।",
  verifyAadhaarFirst: "कृपया पहले अपना आधार का वेरिफिकेशन करें",
  invalidPanNumber: "अमान्य PAN नंबर।",
  goBack: "क्या आप वापस जाना चाहते हैं?",
  goBackPanVerification:
    "यदि आप वापस जाते हैं तो आपका PAN वेरिफिकेशन फिर से करना होगा। अगर आप अपना PAN नंबर बदलना चाहते हैं तो जारी रखें।",
  areThesePanDetails: "क्या यह आपके PAN का विवरण हैं?",
  bankAccountDetails: "बैंक खाते का विवरण",
  referToPassbook:
    "अपने बैंक रिकॉर्ड में उल्लिखित सटीक नाम के लिए अपनी बैंक पासबुक या चेक बुक देखें",
  accountHolderName: "खाता धारक का नाम*",
  bankAccountNumber: "बैंक खाता संख्या*",
  refertoGetAccountNumber:
    "बैंक खाता संख्या प्राप्त करने के लिए अपनी बैंक पासबुक या चेक बुक देखें।",
  ifscCode: "IFSC कोड*",
  findIfscCode:
    "आप बैंक द्वारा प्रदान की गई चेक बुक या बैंक पासबुक पर IFSC कोड पा सकते हैं",
  upiId: "UPI आईडी",
  lotsOfUpiApps:
    "Google Pay, Phonepe, Amazon Pay, Paytm, BHIM, MobiKwik इत्यादि जैसे बहुत सारे UPI ऐप उपलब्ध हैं जहां से आप अपनी UPI आईडी प्राप्त कर सकते हैं।",
  agreeWithKycRegistration:
    "मैं अपनी पहचान वेरीफाई करने के लिए KYC पंजीकरण नियम और शर्तों से सहमत हूं। हम हर महीने आपकी एडवांस सैलरी जमा करने के लिए इस बैंक खाते/UPI आईडी का उपयोग करेंगे, कृपया अपने बैंक खाते का विवरण प्रदान करें।",
  detailsSafe: "आपकी सारी जानकारी हमारे पास सुरक्षित है",
  goBackBankVerification:
    "यदि आप वापस जाते हैं तो आपका बैंक वेरिफिकेशन फिर से करना होगा। अगर आप अपने बैंक खाते के विवरण में बदलाव करना चाहते हैं, तभी जारी रखें।",
  areTheseBankDetails: "क्या यह आपके बैंक खाते का विवरण है?",
  continuePanVerification: "PAN वेरिफिकेशन जारी रखें",
  continueBankVerification: "बैंक वेरिफिकेशन जारी रखें",
  bankName: "बैंक का नाम",
  branchName: "शाखा का नाम",
  branchCity: "शाखा शहर",
  ifscCodeSingle: "आईएफ़एससी",
  upi: "UPI",
  verifyStatus: "स्थिति की पुष्टि करें",
  editProfileDetails: "अपना प्रोफ़ाइल विवरण देखें और बदलाव करें",
  kycDetailsInOnePlace: "आपके सभी KYC विवरण एक ही स्थान पर",
  customerSupport: "ग्राहक सहायता",
  termsAndConditions: "Terms & Conditions",
  privacyPolicy: "Privacy Policy",
  talkToSupportTeam: "हमारी सहायता टीम से बात करें",
  readTermsOfUse: "Terms of use पढ़ें",
  readPrivacyPolicy: "हमारी Privacy Policy पढ़ें",
  logout: "लॉग आउट",
  logoutFromUnipe: "यूनीपे ऐप से लॉग आउट करें",
  choosePreferredMode: "कृपया अपना पसंदीदा तरीका चुनें",
  initializing: "प्रारंभ किया जा रहा है...",
  mandateRegistrationInProgress:
    "आपका मैंडेट पंजीकरण वर्तमान में प्रगति पर है।",
  MandateRequired:
    "देय तिथि पर ऋण भुगतान को ऑटो-डेबिट करने के लिए मैंडेट पंजीकरण आवश्यक है। यह 100% सुरक्षित है और RBI द्वारा अनुमोदित इकाई द्वारा किया जाता है",
  secured: "100% सुरक्षित",
  rbiApproved: "RBI स्वीकृत",
  updatingMandate: "मैंडेट पंजीकरण विवरण अद्यतन करना",
  mayTakeFewSeconds: "इसमें कुछ सेकंड लग सकते हैं",
  dontPressBack: "कृपया बैक बटन ना दबाएं",
  mandateFailed: "मैंडेट पंजीकरण विफल, कृपया पुन: प्रयास करें",
  employeeAddressDetailsRecorded: "कर्मचारी का पता दर्ज किया गया।",
  portal: "पोर्टल",
  familyDetails: "पारिवारिक विवरण",
  yourAddress: "आपका पता",
  nomineeAddress: "नामिती व्यक्ति का पता",
  nomineeAddressDetailsRecorded: "नामिती के पते का विवरण दर्ज किया गया।",
  esicPortalDetailsRecorded: "ESIC पोर्टल विवरण दर्ज किया गया।",
  fatherName: "पिता/पति का नाम*",
  relationWithEmployee: "कर्मचारी (पिता/पति) के साथ संबंध*",
  nameOfNominee: "नॉमिनी का नाम (आधार कार्ड के अनुसार)*",
  nomineeRelationship: "कर्मचारी के साथ नामिती व्यक्ति का संबंध*",
  documents: "दस्तावेज़",
  moreDetailsComingSoon: "अधिक जानकारी जल्द आ रही है",
  dateOfBirth: "लाइसेंस में दर्ज जन्म तिथि",
  licenseNeeded:
    "भारी मशीनरी संचालित करने के लिए अपनी पात्रता को वेरीफाई करने के लिए लाइसेंस की आवश्यकता होती है।",
  expiryDate: "एक्सपायरी डेट",
  nonTransport: "गैर-परिवहन",
  valid: "वैध",
  invalid: "अमान्य",
  licenseDetailsNotEditable:
    "The License Details are not editable, please ask your employer to update",
  unipeP2PHeading:
    "Unipe Invest is a P2P investment that earns you upto 9% interest on your investments",
  poweredByLiquiloans: "We are powered by Liquiloans, RBI regulated P2P NBFC.",
  interestEarned:
    "Interest earned will be earned daily and you are free to withdraw your investment and earnings at any time",
  welcomeToUnipeInvest: "Welcome to Unipe Invest.",
  designedToMultiply: "Designed to multiply your growth",
  knowMore: "Know more",
  youAreOnly: "You are only",
  steps: "2 steps",
  awayFromMakingInvestment: "away from making your first investment",
  proceedToVerifyAndGrowWealth:
    "proceed to verify your details and start growing your wealth.",
  howItWorks: "How it works?",
  joinedWaitlist: "You've joined the waitlist for Unipe Invest!!",
  rbiRegisteredNBFC: "an RBI registered NBFC-P2P",
  p2pInvestment: "What is P2P investment?",
  peerToPeerInvestment:
    "Peer 2 Peer investment allows you to invest money against loans given to borrows and is done by our RBI regulated partner",
  benefitsOfP2P: "What are the benefits of P2P investment?",
  p2pLendingRBI:
    "P2P lending is regulated by RBI. We have partnered with Liquiloans to offer investment products\n\nP2P investment gives opportunity to earn more than traditional deposit products",
  risksOfP2P: "What are the risks associated with P2P investment?",
  p2pRisks:
    "Like any other investment product P2P investment also has associated risk like performance of loans and repayment of borrowers affect your returns\n\nGood News is Our partner has honoured 100% withdrawal within 48 Hrs.\n\nAlso our partner investment product is rated as AA- (by CRISIL) which is one of the highest in the industry",
  whyInvestWithUnipe: "Why invest with Unipe?",
  earnHighReturns:
    "You can earn inflation beating highest returns for your investment\n\nYour principal and base interest is secured at our RBI regulated partner",
  knowMoreAboutP2P: "Know more about P2P investment",
  howMuch: "आप कितनी राशि निकालना चाहते हैं?",
  accessOfEF: "यह रही आपकी आपातकालीन राशि",
  zeroInterest: "शून्य ब्याज शुल्क, नाममात्र की प्रोसेसिंग फीस",
  iAgree: "मैं नियमों और शर्तों से",
  TermsAndConditions: "सहमत हूं",
  processing: "प्रोसेसिंग",
  areTheseKycDetails: "क्या यह आपके KYC का विवरण हैं?",
  processingFees: "प्रोसेसिंग फीस †",
  disAmount: "भुगतान राशि*",
  loanAmount: "ऋण की राशि",
  dueDate: "नियत तारीख",
  loanDetails: "ऋण विवरण",
  bankDetails: "बैंक विवरण",
  moneyWillBeAutoDebited:
    "*राशि या तो आपके खाते से स्वतः डेबिट हो जायेगी या आपकी कंपनी द्वारा आपके आगामी वेतन से काट ली जाएगी।",
  personalDetails: "व्यक्तिगत विवरण",
  aboveDetails: "मैं उपरोक्त विवरण की पुष्टि करता हूं और इससे सहमत हूं",
  apr: "† सालाना प्रतिशत दर @",
  congrats: "बधाई हो",
  advanceSalaryCredited:
    "आपकी एडवांस सैलरी आपके बैंक खाते में जमा करा दी गई है।",
  sorry: "माफ़ कीजिये",
  cannotProcessSalary: "हम इस समय आपके अग्रिम वेतन को प्रोसेस नहीं कर सकते।",
  pending: "पेंडिंग",
  receiveMoney: "आपको अगले 24 बैंकिंग घंटों में राशि प्राप्त होगी।",
  netTransferAmount: "नेट ट्रांसफर राशि",
  loanAccountNumber: "ऋण खाता संख्या",
  transferStatus: "ट्रांसफर की स्थिति",
  moneyAutoDebitedUpcomingSalary:
    "आपके आने वाले वेतन से राशि स्वतः डेबिट हो जाएगी",
  onDemandSalary: "यह रही आपकी ऑन-डिमांड सैलरी",
  totalAmountDue: "आपकी कुल बकाया राशि",
  RepaymentDue: "आपका पुनर्भुगतान <> दिनों से बकाया है",
  pastDraws: "आपके पिछले विथड्रॉवल्स",
  getYourSalaryToday: "आज ही अपना वेतन प्राप्त करें!",
  enterMobileNumber: "मोबाइल नंबर दर्ज करें",
  getAdvancedSalaryToday: "आज ही अपना अग्रिम वेतन\n प्राप्त करें",
  zeroInterestCharge: "0% ब्याज शुल्क",
  noJoiningFees: "कोई जॉइनिंग फीस नहीं",
  interestInBank: "बैंक खाते में तत्काल नकद",
  pleaseWaitOtp:
    "कृपया प्रतीक्षा करें, हम भेजे गए ओटीपी को स्वतः सत्यापित करेंगे",
  verifyMobileNumber: "मोबाइल नंबर सत्यापित करें",
  resendOtp: "ओटीपी पुनः भेजें",
  didnotReceiveOtp: "सुरक्षित कोड प्राप्त नहीं हुआ?",
  resendOtpIn: "Resend OTP in",
  aadhaarVerification: "आधार सत्यापन",
  enterYourDetails: "अपना विवरण दर्ज करें",
  verifyAadhaar: "आधार सत्यापित करें",
  panVerification: "पैन कार्ड सत्यापन",
  addBankAccount: "बैंक खाता जोड़ें",
  onDemandSalary: "ऑन-डिमांड वेतन",
  selectAmount: "वह राशि चुनें जिसे आप निकालना चाहते हैं",
  confirmKyc: "केवाईसी की पुष्टि करें",
  confirmIfTheseDetails: "कृपया पुष्टि करें कि क्या ये आपके विवरण हैं",
  confirmMyKyc: "मैं अपने केवाईसी की पुष्टि करता हूं",
  verifying: "सत्यापन",
  addRepaymentMethod: "चुकौती विधि जोड़ें",
  faq: "अक्सर पूछे जाने वाले सवाल",
  proceed: "आगे बढ़ें",
  name: "नाम",
  panNumber: "पैन नंबर",
  dateOfBirth: "जन्म की तारीख",
  moneyTransfer: "मनी ट्रांसफर",
  verifyYourIdentity:
    "अपनी पहचान की पुष्टि करें और अग्रिम वेतन निकालने के लिए अपनी पूर्ण केवाईसी प्रक्रिया पूरी करें।",
  availableSalary: "उपलब्ध वेतन",
  withDrawAdvanceSalary: "अग्रिम वेतन वापस लें",
  kycPending: "अग्रिम वेतन के लिए केवाईसी लंबित",
  offerInactive: "प्रस्ताव निष्क्रिय",
  getSalaryNow: "अभी वेतन प्राप्त करें",
  completeYourKyc: "अपना केवाईसी पूरा करें",
  transfer: "ट्रांसफर करे",
  toBankAccount: "आपके बैंक खाते में मिनटों में",
  payNow: "भुगतान करें",
  inProgress: "प्रगति पर है",
  iWantToWithdraw: "I want to withdraw",
  bankAccount: "बैंक खाता",
  takeBusinessDays: "1 कार्य दिवस तक लेता है",
  withdrawalDeduction: "निकासी को आपके आगामी पेचेक से काट लिया जाएगा",
};
